# Generated by Django 4.2.4 on 2023-09-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_number', models.PositiveIntegerField()),
                ('status', models.TextField()),
                ('mathod_of_payment', models.CharField(max_length=32)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
