# Generated by Django 4.2.4 on 2023-09-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='mathod_of_payment',
            new_name='payment',
        ),
    ]
